version: "2.4"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=main.py
    networks:
      - app-network
    command: flask run --host=0.0.0.0 --port=5000

networks:
  app-network: