version: "2.4"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=main.py
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/app_db}
    networks:
      - app-network
    restart: unless-stopped
    command: python main.py

networks:
  app-network: